### ISSUE TITLE
NativeClass methods are not there in CPP files ? 

### ISSUE THREAD

**Issue by srikanth104** [zinia94/EyeWarning#1]

**Comment by zinia94** [comment]
By using NDK , shared library is created from a CPP file. That library is loaded later in the MainActivity. That CPP file contains the methods in NativeClass.

**Comment by srikanth104** [comment]
Ok, Somehow it's not working for me and it's not loading OpenCV even after changing CMakelist.txt. So I'm assuming issue is at my end and I need your help to configure the application to understand the flow. So can you please ping me on srikanth.vusikarla@gmail.com

**Comment by smwm674** [comment]
I need your help to configure the application to understand the flow. So can you please ping me on smwm674@gmail.com
